import initSchemaRelationship from "../InitialDBSetup/initSchemaRelationship";
import { logInfo } from "../utils/helper";

class TestService {
	static async run() {
		initSchemaRelationship();
		let checkStyle = [
			"illusion",
			"double",
			"6 prong",
			"single",
			"hidden",
			"crown",
			"8 prong",
			"vintage",
			"traditional",
			"chokar",
			"drop",
			"with bail",
			"8 prong",
			"single",
			"halo",
			"personalized",
			"half",
			"cocktail",
			"double",
			"eternity",
			"joint ring",
			"solitaire",
			"cluster",
			"single",
			"illusion",
			"sidestones",
			"illusion",
			"two lock",
			"6 prong",
			"cuban",
			"fancy",
			"medallion",
			"multilayer",
			"traditional",
			"adjustable",
			"bezel",
			"jacket",
			"cocktail",
			"rivera",
			"plug",
			"hoop",
			"pave",
			"open bangle",
			"bypass",
			"vintage",
			"floral",
			"personalized",
			"illusion",
			"climber",
			"double",
			"birth stone",
			"cluster",
			"double",
			"wrap",
			"locket",
			"c hoop",
			"huggie",
			"single lock",
			"designer",
			"half",
			"statement",
			"hip hop",
			"basket",
			"stackable",
			"art deco",
			"designer",
			"half",
			"cuff",
			"tension",
			"miligrain",
			"slide",
			"basket",
			"photo",
			"adjustable",
			"station",
			"chain",
			"illusion",
			"full",
			"curved",
			"decorative",
			"fingernail",
			"roundel",
			"cluster",
			"hidden",
			"bar",
			"bezel",
			"signet",
			"adjustable",
			"tiffiny",
			"4 prong",
			"cuban",
			"solitair",
			"cross over",
			"chandelier",
			"hugging",
			"crown",
			"three stones",
			"hugging",
			"toe",
			"stacking",
			"cluster",
			"leverback",
			"charm",
			"tennis",
			"tennis",
			"bezel",
			"layering",
			"unique",
			"plain",
			"martini",
			"6 prong",
			"two shapes",
			"personalized",
			"drop",
			"basket",
			"charm",
			"trellis",
			"hidden bail",
			"full",
			"four row",
			"rivera",
			"love",
			"tear drop",
			"channel",
			"triple",
			"dangle",
			"watch belt",
			"4 prong",
			"lariat",
			"single",
			"solitaire",
			"bezel",
			"religious",
			"drop",
			"chain",
			"designer",
			"adjustable",
			"double",
			"bridge",
			"birthstone",
			"designer",
			"alternat 3",
			"single",
			"full",
			"hidden",
			"stud",
			"chain",
			"traditional",
			"halo",
			"full",
			"decorative",
			"bangle",
			"full",
			"wrap",
			"halo",
			"threader",
			"chevron",
			"religious",
			"wire hook",
			"channel",
			"hugging",
			"traceble",
			"half",
			"martini",
			"triple",
			"love",
			"decorative",
			"8 prong",
			"engravable",
			"three stone",
			"twisted",
			"double",
			"bar",
			"half",
			"alternat 3",
			"clicker",
			"four row",
			"single",
			"4 prong",
			"pendant",
		];

		console.log(checkStyle.includes("pendant"));
	}
}

TestService.run();
